/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PeopleListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThePeopleList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThePeopleList.onFilterBar().iCheckFilterField("UserName");
            Then.onThePeopleList.onFilterBar().iCheckFilterField("FirstName");
            Then.onThePeopleList.onFilterBar().iCheckFilterField("LastName");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThePeopleList.onTable().iCheckColumns(undefined, {"UserName":{"header":"Username"},"FirstName":{"header":"First Name"},"LastName":{"header":"Last Name"},"Gender":{"header":"Gender"},"Email":{"header":"Email"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onThePeopleList.onFilterBar().iExecuteSearch();
            
            Then.onThePeopleList.onTable().iCheckRows();

            When.onThePeopleList.onTable().iPressRow(0);
            Then.onThePeopleObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});