/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PeopleObjectPageObjectPage journey");

        opaTest("Navigate to PeopleObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThePeopleList.onFilterBar().iExecuteSearch();

            Then.onThePeopleList.onTable().iCheckRows();
            When.onThePeopleList.onTable().iPressRow(0);

            Then.onThePeopleObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePeopleObjectPage.iCheckSection({ section: "FieldGroup::PersonDetails" });
            Then.onThePeopleObjectPage.onForm({ section: "FieldGroup::PersonDetails" }).iCheckField({ property: "UserName" });
            Then.onThePeopleObjectPage.onForm({ section: "FieldGroup::PersonDetails" }).iCheckField({ property: "FirstName" });
            Then.onThePeopleObjectPage.onForm({ section: "FieldGroup::PersonDetails" }).iCheckField({ property: "LastName" });
            Then.onThePeopleObjectPage.onForm({ section: "FieldGroup::PersonDetails" }).iCheckField({ property: "Gender" });
            Then.onThePeopleObjectPage.onForm({ section: "FieldGroup::PersonDetails" }).iCheckField({ property: "Email" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});